function showCORAClusters(cora, d)

%cora = slurpCORA();
[coeffs,score,~,~,explanation,mu] = pca(double(cora.paperWords));

i = cora.paperClass;

if d==2

plot(...
  score(i==1,1),score(i==1,2),'.b', ...
  score(i==2,1),score(i==2,2),'.r', ...
  score(i==3,1),score(i==3,2),'.g', ...
  score(i==4,1),score(i==4,2),'.k', ...
  score(i==5,1),score(i==5,2),'.c', ...
  score(i==6,1),score(i==6,2),'.m', ...
  score(i==7,1),score(i==7,2),'.y');

else

plot3(...
  score(i==1,1),score(i==1,2),score(i==1,3),'.b', ...
  score(i==2,1),score(i==2,2),score(i==2,3),'.r', ...
  score(i==3,1),score(i==3,2),score(i==3,3),'.g', ...
  score(i==4,1),score(i==4,2),score(i==4,3),'.k', ...
  score(i==5,1),score(i==5,2),score(i==5,3),'.c', ...
  score(i==6,1),score(i==6,2),score(i==6,3),'.m', ...
  score(i==7,1),score(i==7,2),score(i==7,3),'.y');

end

axis equal;

